name: Package Application with Pyinstaller

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r common.zip common
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/windows/MHWStoreModuleManager.exe,common.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
